### PR TITLE
add createKey method

### PR DESCRIPTION
**Pull request by macbookandrew**

### CODE REVIEW

**Comment by mhetreramesh** [comment]
Hi @macbookandrew,

Can you describe your change for better understanding?

**Comment by macbookandrew** [comment]
Sure—sorry, I should have included that to start with. There are two changes in this PR:

1. Add a `createKey` method to create [Application Keys](https://help.backblaze.com/hc/en-us/articles/360052129034-Creating-and-Managing-Application-Keys)
    - Should I add some tests for this?
1. Add more detail to the bucket API calls so consuming code can determine whether the bucket is S3-compatible and get other bucket options

**Comment by ersin-comet** [comment]
Hello @mhetreramesh  @macbookandrew 

This is useful for my current work, thanks for taking the time to work on this!

I have been able to integrate and use this new method, but noticed there is a minor issue with the `Key` class.

When I call `$client->create_key($options)` I expect that the created key instance has the correct value returned for `getName()` and `getSecret()` methods, however it appears that these keys are swapped around.

What can I do to get this merged upstream?

**Comment by macbookandrew** [comment]
@ersin-comet Thanks.

> however it appears that these keys are swapped around.

You’re right…fixed in https://github.com/gliterd/backblaze-b2/pull/56/commits/6edc18cb1b88a0dfe9257d76b5c79f50e53460cd

I also added `listKeys()` and `deleteKey()` methods.

**Comment by macbookandrew** [comment]
@mlambley Just curious—did I miss something you wanted in order to merge this? Or would you prefer to keep application keys management out of this package?

**Comment by mlambley** [comment]
@macbookandrew I didn't mean to delete this sorry. You will have to recreate the PR.

**Comment by mlambley** [comment]
@macbookandrew Then tag me in the new PR and I'll review it.

**Pull request closed without merging**
