### PR TITLE
Add support for re-authorization after a timeout period

### PR DESCRIPTION
**Pull request by kenrowland**
Signed-off-by: kenrowland <rowlandkenneth@gmail.com>

### CODE REVIEW

**Comment by kenrowland** [comment]
@mhetreramesh I do not know why the CI test is reporting the problem it is, but the line is required.

**Comment by mhetreramesh** [comment]
It is because of new package has a minimum requirement of having php version of 7.1.8 which breaks Travis build for version 5.6([Details](https://travis-ci.org/gliterd/backblaze-b2/jobs/478381211)).

Seems like to merge this pull request we will have to remove support for php 5.6

I'll think about it over the weekend and lets see if we can remove php 5.6 support.

**Comment by kenrowland** [comment]
@mhetreramesh I do not have a need for php 5.6 if that helps

**Comment by dylanhansch** [comment]
Since php 5.6 is EOL now (and not getting security fixes either) no one
should be running it anyway. I'd say it's safe to drop 5.6 support. 👍

**Pull request merged**
